# Generated by Django 3.1.4 on 2020-12-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trasaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_from', models.CharField(max_length=32)),
                ('trans_to', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
